# This file was generated by GoReleaser. DO NOT EDIT.
cask "fury-cli" do
  version "1.0.0-beta.1"

  on_macos do
    sha256 "eb91db5a72e7eb1bc34c8c9bda8718ab1f0907af5b3a050a21618a7ae095ea7d"
    url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_macOS_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "a17c522a6675b51ac9a6e2d7b1d64cf53858e31633b61f6fd40750e43e32e7f3"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "0842530d8c99365da99709bc37d3a9dee6ce10104bb021fd36856d31c7e6cf25"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "fury-cli"
  desc "CLI for the Gemfury package repository"
  homepage "https://gemfury.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fury"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/fury"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the "fury" binary and cannot coexist with the
    legacy Ruby "gemfury" formula. Uninstall it first if present.
  EOS
end
