# This file was generated by GoReleaser. DO NOT EDIT.
cask "fury-cli" do
  version "0.25.0"

  on_macos do
    sha256 "fd0f7ab3b0dc9d44004caf847d255ee7c6755faba00c486db62a23a5ee5b7d81"
    url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_macOS_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "4c5624b1069ff75a161bda763d2adc7666836cc16e7ada9ac68daf56166cb34b"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "e66a22314819410a28310d8a10cdd8ce2fbf0b90584bdb87688e047d37851005"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "fury-cli"
  desc "CLI for the Gemfury package repository"
  homepage "https://gemfury.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fury"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/fury"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the "fury" binary and cannot coexist with the
    legacy Ruby "gemfury" formula. Uninstall it first if present.
  EOS
end
