# This file was generated by GoReleaser. DO NOT EDIT.
cask "fury-cli" do
  version "0.26.0-beta.1"

  on_macos do
    sha256 "d9ae8bf5023a36a301c501359bc6fb1673a8f213a19953c3782e8cec924015d5"
    url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_macOS_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "4cb4a300fdbb3b3815de6c0bf654a49a7bd317e94a9b4ae0a15bbc23b42ecc7e"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_ARM64.tar.gz"
    end
    on_intel do
      sha256 "15dde6a10574c6fbe6890f2c48b2e5d5d2f8ed6bae4cb14fccd1bcb67f073bca"
      url "https://github.com/gemfury/cli/releases/download/v#{version}/fury-cli_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "fury-cli"
  desc "CLI for the Gemfury package repository"
  homepage "https://gemfury.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fury"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/fury"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This cask installs the "fury" binary and cannot coexist with the
    legacy Ruby "gemfury" formula. Uninstall it first if present.
  EOS
end
