# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuryCli < Formula
  desc "CLI for the Gemfury package repository"
  homepage "https://gemfury.com/"
  version "0.25.0"

  on_macos do
    url "https://github.com/gemfury/cli/releases/download/v0.25.0/fury-cli_0.25.0_macOS_universal.tar.gz"
    sha256 "fd0f7ab3b0dc9d44004caf847d255ee7c6755faba00c486db62a23a5ee5b7d81"

    define_method(:install) do
      bin.install "fury"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gemfury/cli/releases/download/v0.25.0/fury-cli_0.25.0_Linux_x86_64.tar.gz"
      sha256 "e66a22314819410a28310d8a10cdd8ce2fbf0b90584bdb87688e047d37851005"
      define_method(:install) do
        bin.install "fury"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gemfury/cli/releases/download/v0.25.0/fury-cli_0.25.0_Linux_ARM64.tar.gz"
      sha256 "4c5624b1069ff75a161bda763d2adc7666836cc16e7ada9ac68daf56166cb34b"
      define_method(:install) do
        bin.install "fury"
      end
    end
  end

  conflicts_with "gemfury"

  def caveats
    <<~EOS
      The fury-cli formula will be replaced by a cask in an upcoming release.
      To switch early: brew uninstall fury-cli && brew install --cask gemfury/tap/fury-cli
    EOS
  end

  test do
    system "#{bin}/fury --version"
  end
end
