# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuryCli < Formula
  desc "CLI for the Gemfury package repository"
  homepage "https://gemfury.com/"
  version "0.24.1"

  on_macos do
    url "https://github.com/gemfury/cli/releases/download/v0.24.1/fury-cli_0.24.1_macOS_universal.tar.gz"
    sha256 "96eb974e2fcadeb59b220b040f33f6bd4a2d3ae8937dcd13be49f6a2f4c53f1c"

    define_method(:install) do
      bin.install "fury"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gemfury/cli/releases/download/v0.24.1/fury-cli_0.24.1_Linux_x86_64.tar.gz"
      sha256 "34e722f22ddb657e67dcb8acea1986fc51ec9cadb73c25def554d6082fce0897"
      define_method(:install) do
        bin.install "fury"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gemfury/cli/releases/download/v0.24.1/fury-cli_0.24.1_Linux_ARM64.tar.gz"
      sha256 "b3e9d7bca4032016fb26c5cb053affb7df97b99ce61865e9f302d76937e32607"
      define_method(:install) do
        bin.install "fury"
      end
    end
  end

  conflicts_with "gemfury"

  def caveats
    <<~EOS
      The fury-cli formula will be replaced by a cask in an upcoming release.
      To switch early: brew uninstall fury-cli && brew install --cask gemfury/tap/fury-cli
    EOS
  end

  test do
    system "#{bin}/fury --version"
  end
end
